driver: chdkcamera
plugins:
    - hidtrigger
    - web
core:
    verbose: yes
    logfile: /home/spreads/.config/spreads/spreads.log
    capture_keys: [' ', b]
    loglevel: debug
device:
    flip_target_pages: no
    parallel_capture: yes
web:
    project_dir: /home/spreads/scans
    debug: yes
    standalone_device: yes
    mode: scanner
