#!/bin/sh

if [ ! -f /etc/.part_resized ]; then
    # Return value will likely be error for fdisk as it fails to reload the
    # partition table because the root fs is mounted
    fdisk /dev/mmcblk0 <<EOF
p
d
2
n
p
2


p
w
EOF

    touch /etc/.part_resized
    systemctl reboot
elif [ ! -f /etc/.fs_resized ]; then
    resize2fs /dev/mmcblk0p2
    touch /etc/.fs_resized
fi
