#!/bin/sh

### BEGIN INIT INFO
# Provides: resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5 S
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting resize2fs_once" &&
        resize2fs /dev/mmcblk0p2 &&
        rm /etc/init.d/resize2fs_once &&
        update-rc.d resize2fs_once remove &&
        log_end_msg $?
        ;;
    *)
        echo "Usage: $0 start" >&2
        exit 3
        ;;
esac

